root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/notification-service ./cmd/main.go"
bin = "tmp/notification-service"
full_bin = "tmp/notification-service"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp"]
delay = 1000
stop_on_error = true

[log]
color = true
timestamp = true

[misc]
clean_on_exit = true
